pieline {
  aget any
  stages {
    stage('git erpo & clean') {
      steps {
        bat "git clone https://github.com/tenasik/Pipeline-maven/edit/master/Kisanet/G/Jenkinsfile'
  }
    }
  stage ('Build'){
    steps {
      bat " Build the project"
      }
  }
     stage ('Test'){
    steps {
      bat " Test the project"
      }
         }
      stage ('Build'){
    steps {
      bat " Build the project"
      }
         
         }
  }
}
    
