pieline {
  aget any
  stages {
    stage('git repo & clean') {
      steps {
        bat "git clone https://github.com/tenasik/Pipeline-maven.git'
  }
    }
  stage ('Build'){
    steps {
      bat " Build the project"
      }
  }
     stage ('Test'){
    steps {
      bat " Test the project"
      }
         }
      stage ('Build'){
    steps {
      bat " Build the project"
      }
         
         }
  }
}
    
